### PR TITLE
Added orders on SeedFu

### PR DESCRIPTION
**Pull request by ogom**
SeedFu is very powerful. 
But, I want to specify the order. 

It's implement the order in compatibility.
Set orders in an array order.

```
SeedFu.orders << 'users'
SeedFu.orders << 'accounts'
SeedFu.orders << 'products'
```

Best regards

### CODE REVIEW

**Comment by NaturalHokke** [comment]
+1

**Comment by takashi** [comment]
+1

**Comment by deastman** [comment]
+1

**Comment by ogom** [comment]
It seems there is no need for updating, so close it.

**Pull request closed without merging**
