### PR TITLE
update dependencies for Rails 4.2.x

### PR DESCRIPTION
**Pull request by y-yagi**

### CODE REVIEW

**Comment by yatmsu** [comment]
:+1:

**Comment by chulkilee** [comment]
@mbleigh can you merge this and release the new version? Rails 4.2.1 app uses seed-fu 1.x due to this bug.

**Comment by dbackowski** [comment]
:+1:

**Comment by fantasticfears** [comment]
:+1:

**Comment by fukayatsu** [comment]
+1

**Comment by tatsuo** [comment]
:+1:

**Comment by satoruk** [comment]
+1

**Comment by derekkraan** [comment]
:+1:

**Comment by hugocorbucci** [comment]
:+1:

**Comment by trobrock** [comment]
@mbleigh anything we can do to help get this released?

**Comment by y-yagi** [comment]
Thanks!

**Comment by dbackowski** [comment]
Please release version 2.3.5 as gem.

**Comment by aserafin** [comment]
it's there: https://rubygems.org/gems/seed-fu/versions/2.3.5 :)

**Comment by dbackowski** [comment]
Thanks

**Pull request merged**
