### PR TITLE
Add support for default scope/scope overrides

### PR DESCRIPTION
**Pull request by joshuawscott**
I had a use case where I needed to soft-delete some seed data using the paranoia gem, which scopes everything to `WHERE deleted_at IS NULL`.  On subsequent runs, the `rake db:seed_fu` would raise an error because it would try to `find` the record, and because of the scoping, it would not find it, so it would attempt to create a new record with that id.  The id still existed in the database, and since it is a primary key, it would raise an error.

This change calls `unscoped` to ensure that duplicate records aren't added when `default_scope` or soft-delete gems are being used.

### CODE REVIEW

**Comment by fregas** [comment]
Is this ever going to be merged?

**Comment by noafroboy** [comment]
Is this ever going to be merged?

**Comment by joshuawscott** [comment]
If I need to rebase this or something, I'm happy to do it, just let me know.

**Comment by noafroboy** [comment]
@mbleigh ping

**Comment by joshuawscott** [comment]
@mbleigh Pulled in the changes from master and @mcmoyer removed the protected_attributes dependency that I had apparently added. Any chance of getting this merged?

**Comment by joshuawscott** [comment]
Closing this, as we can use `Model.with_deleted.seed` to seed without any other changes

**Pull request closed without merging**
